/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import CONEXION.CONECTAR;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class REGISTRO_PRODUC extends javax.swing.JFrame {

    //esta es nuestra conexion con nuestra clase conectar
    //para poder tener acceso a la base de datos
    CONECTAR enlace = new CONECTAR();
        Connection conect = enlace.conectar();
        
    public REGISTRO_PRODUC() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NUMPRODUC = new javax.swing.JTextField();
        PRODUCTO = new javax.swing.JTextField();
        EMPRESA = new javax.swing.JTextField();
        ORIGEN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_PRODUCTOS = new javax.swing.JTable();
        GUARDAR = new javax.swing.JButton();
        ACTUA = new javax.swing.JButton();
        LIMPIAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TIPO = new javax.swing.JComboBox<>();
        PRECIO = new javax.swing.JTextField();

        jButton4.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NªPRODUCTO");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("PRECIO $");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("PRODUCTO");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("EMPRESA");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("HECHA EN");

        jPanel3.setBackground(new java.awt.Color(84, 164, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/hombre.png"))); // NOI18N
        jLabel1.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        NUMPRODUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMPRODUCActionPerformed(evt);
            }
        });

        TABLA_PRODUCTOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TABLA_PRODUCTOS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLA_PRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TABLA_PRODUCTOS);

        GUARDAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar-el-archivo.png"))); // NOI18N
        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        ACTUA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ACTUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/editar.png"))); // NOI18N
        ACTUA.setText("ACTUALIZAR");
        ACTUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUAActionPerformed(evt);
            }
        });

        LIMPIAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LIMPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/limpiar.png"))); // NOI18N
        LIMPIAR.setText("LIMPIAR");
        LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIARActionPerformed(evt);
            }
        });

        ELIMINAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/borrar.png"))); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("TIPO");

        TIPO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Periferico", "Pantallas", "Procesador", "Ram", "Almacenamiento", "Fuente", "" }));
        TIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ORIGEN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NUMPRODUC, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(PRODUCTO, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EMPRESA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PRECIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(GUARDAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACTUA)
                .addGap(18, 18, 18)
                .addComponent(LIMPIAR)
                .addGap(18, 18, 18)
                .addComponent(ELIMINAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NUMPRODUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EMPRESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ORIGEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUARDAR)
                    .addComponent(ACTUA)
                    .addComponent(LIMPIAR)
                    .addComponent(ELIMINAR))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUMPRODUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMPRODUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMPRODUCActionPerformed

    //al presu
    private void ACTUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUAActionPerformed
        ACTUALIZAR();
    }//GEN-LAST:event_ACTUAActionPerformed

    private void TIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPOActionPerformed
//este metodo permite limpiar los campos
    private void LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPIARActionPerformed
          NUMPRODUC.setText("");
        PRODUCTO.setText("");
       //TIPO.setText("");
       EMPRESA.setText("");
      PRECIO.setText("");
       ORIGEN.setText("");
    }//GEN-LAST:event_LIMPIARActionPerformed

    
    //con este boton guardaremos los datos ingresados en nuestra tabla productos
    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
      String tipo_pro ;
      
        
        
        try {
            PreparedStatement guardar = conect.prepareStatement("INSERT INTO producto(id_produc,producto,tipo,empresa,precio,lugar_fabri)VALUES(?,?,?,?,?,?)");
                    
            guardar.setString(1,NUMPRODUC.getText());
            guardar.setString(2,PRODUCTO.getText());
             guardar.setString(3,TIPO.getSelectedItem().toString());
            guardar.setString(4,EMPRESA.getText());
           guardar.setString(5,PRECIO.getText());
            guardar.setString(6,ORIGEN.getText());
           guardar.executeUpdate();
           JOptionPane.showMessageDialog(null,"REGISTRO GUARDADO CON EXITO") ;
           
           
            
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,e+" no se logro registrar") ;
        }
               
mostrar();  
    }//GEN-LAST:event_GUARDARActionPerformed

    //con este metodo podremos cojer los datos que estan en el sistema modificarlos y guardarlos nuevamente
    //usando de referencia el id del producto que es quien lo identifica
    public void ACTUALIZAR(){
    int fila= TABLA_PRODUCTOS.getSelectedRow();
    String id = (String) TABLA_PRODUCTOS.getValueAt(fila,0);
    String PRODUC= TABLA_PRODUCTOS.getValueAt(fila,1).toString();
    String TIP= TABLA_PRODUCTOS.getValueAt(fila,2).toString();
    String EMPRES= TABLA_PRODUCTOS.getValueAt(fila,3).toString();
   String PRECI= TABLA_PRODUCTOS.getValueAt(fila,4).toString();
    String ORIGE= TABLA_PRODUCTOS.getValueAt(fila,5).toString();
    
    try{
        PreparedStatement actu = conect.prepareStatement("UPDATE producto SET id_produc='"+id+"',producto='"+PRODUC+"',tipo='"+TIP+"',empresa='"+EMPRES+"',precio='"+PRECI+"',lugar_fabri='"+ORIGE+"' WHERE id_produc='"+id+"'");
        actu.executeUpdate();
        JOptionPane.showMessageDialog(null,"SE ACTUALIZO :3") ;
    }catch(SQLException e){JOptionPane.showMessageDialog(null,e+" no se logro actualizar") ;} 
    mostrar();          

    }
    
    //con este boton al presionarlo podremos borrar toda la fila que estemos buscando borrar
    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
       eliminar_producto();
    }//GEN-LAST:event_ELIMINARActionPerformed

  //este metodo nos servira para poder mostrar los datos de la base de datos y verlos en una tabla asi verlos todos  
    public void mostrar (){
DefaultTableModel TABLA = new  DefaultTableModel();
TABLA.addColumn("ID_PRODUCTO");
TABLA.addColumn("PRODUCTO");
TABLA.addColumn("TIPO");
TABLA.addColumn("EMPRESA");
TABLA.addColumn("PRECIO");
TABLA.addColumn("ORIGEN");

TABLA_PRODUCTOS.setModel(TABLA);

String[]datos = new String[8];
try{
    Statement leer = conect.createStatement();
    ResultSet resultado = leer.executeQuery("SELECT*FROM PRODUCTO");
    while(resultado.next()){
    datos[0]=resultado.getString(1);
    datos[1]=resultado.getString(2);
    datos[2]=resultado.getString(3);
    datos[3]=resultado.getString(4);
    datos[4]=resultado.getString(5);
    datos[5]=resultado.getString(6);
    TABLA.addRow(datos);
            }
    TABLA_PRODUCTOS.setModel(TABLA);
}catch(SQLException e){
JOptionPane.showMessageDialog(null,e+" error en la consulta") ;
}
}

    //este metodo cumple la funcion de que coje una fila de datos y si el id que esta es igual al de la tabla en mysql
    //borrar esa fila de datos asi se evita que borre datos de otras filas
public void eliminar_producto(){
int fila= TABLA_PRODUCTOS.getSelectedRow();
 String valor = (String) TABLA_PRODUCTOS.getValueAt(fila,0);
 try{
     PreparedStatement elimi= conect.prepareStatement("DELETE FROM producto WHERE ID_PRODUC='"+valor+"'");
     elimi.executeUpdate();
      JOptionPane.showMessageDialog(null,"SE ELIMINO CON EXITO :V") ;
 }catch(SQLException e){
     JOptionPane.showMessageDialog(null,e+" no se logro eliminar");
 }
 mostrar();      

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PRODUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PRODUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PRODUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PRODUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRO_PRODUC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUA;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JTextField EMPRESA;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton LIMPIAR;
    private javax.swing.JTextField NUMPRODUC;
    private javax.swing.JTextField ORIGEN;
    private javax.swing.JTextField PRECIO;
    private javax.swing.JTextField PRODUCTO;
    private javax.swing.JTable TABLA_PRODUCTOS;
    private javax.swing.JComboBox<String> TIPO;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
